name: Compile mod (Desktop + Android)

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Клонирует репозиторий на runner
    - name: Download repository
      uses: actions/checkout@v4

    # 2️⃣ Устанавливает Java 17 через Temurin JDK
    - name: Installs Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    # 3️⃣ Устанавливаем Android SDK ради компиляции d8
    - name: Installing the Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: 34.0.0

    # 4️⃣ Добавляем Build Tools в PATH как переменную среду
    - name: Configuring android
      run: echo "$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH

    # 5️⃣ Делаем gradlew исполняемым, на Linux так надо
    - name: Configuring gradlew
      run: chmod +x gradlew

    # 6️⃣ Собираем обычный jar через Gradle при помощи build.gradle
    - name: Compiling Desktop jar
      run: ./gradlew clean jar

    # 7️⃣ Конвертируем jar в classes.dex
    - name: Convert jar -> dex
      run: |
        mkdir -p build/temp
        $ANDROID_HOME/build-tools/34.0.0/d8 --output build/temp build/libs/*.jar

    # 8️⃣ Собираем универсальный jar (Desktop + Android + assets + mod.hjson)
    - name: Compiling jar
      run: |
        unzip build/libs/*.jar -d build/temp
        cd build/temp
        zip -r ../ARX-Alpha-Mod.jar .

    # 9️⃣ Загружаем готовый универсальный jar как артефакт
    - name: Uploading artifact
      uses: actions/upload-artifact@v4
      with:
        name: ARX-Alpha-Mod
        path: build/ARX-Alpha-Mod.jar
